name: Test setup-php with PHP 8.1

on: [push, pull_request]

jobs:
  test:
    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'

    steps:
      - name: Check for redis files before setup-php
        if: ${{ !cancelled() }}
        run: find /etc/php -name \*redis\*

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: max_input_vars=5000

      - name: Check for redis files after setup-php
        if: ${{ !cancelled() }}
        run: find /etc/php -name \*redis\*

      - name: Make sure cancelled jobs are marked as failures.
        if: ${{ cancelled() }}
        run: exit 1
